#!/bin/sh

echo "prepare-commit-msg hook script is running"

commit_msg_file="$1"
commit_msg_type="$2"
commit_msg="$3"

if [ "$commit_msg_type" = "-m" ]; then
  echo "$commit_msg" > "$commit_msg_file"
fi

commit_msg=$(cat "$commit_msg_file")

commit_msg_regex=$(cat "$(dirname "$0")/../../.git/hooks/commit-regular.txt")

if ! echo "$commit_msg" | grep -Eq "$commit_msg_regex"; then
  echo "Invalid commit message format."
  cat "$(dirname "$0")/../../.git/hooks/commit-msg-template.txt"
  echo
  exit 1
fi